# Generated by Django 5.2.6 on 2025-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnm', models.CharField(max_length=20)),
                ('lnm', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.BigIntegerField()),
                ('cpassword', models.BigIntegerField()),
            ],
        ),
    ]
