# Generated by Django 5.2.6 on 2025-09-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userdata_cpassword_alter_userdata_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdata',
            new_name='userrdata',
        ),
    ]
