# Generated by Django 5.2.7 on 2025-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnm', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.BigIntegerField()),
                ('pas', models.CharField(max_length=10)),
            ],
        ),
    ]
